version: 2
jobs:
  budowanie_super_aplikacji_wow:
    docker:
    - image: circleci/openjdk:8u171-jdk
      environment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root

    - image: circleci/postgres:9.6.5-alpine-ram
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb

    working_directory: ~/customer-app


    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn clean install
    - persist_to_workspace:
        root: target
        paths:
          - customer-app-0.0.1-SNAPSHOT.jar

  deploy:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - attach_workspace:
        at: ~/customer-app/target
    - run: ls



workflows:
  version: 2
  build-deploy:
    jobs:
    - budowanie_super_aplikacji_wow
    - hold:
        type: approval
        requires:
        - budowanie_super_aplikacji_wow
    - deploy:
        requires:
        - hold
        filters:
          branches:
            only: master