version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u171-jdk
      environment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root
        CLOUDAMQP_URL: amqp://localhost:5672

    - image: circleci/postgres:9.6.5-alpine-ram
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb
      ports:
      - "15672:15672"
      - "5672:5672"

    - image: rabbitmq:3.6-management-alpine
      environment:


    working_directory: ~/customer-app


    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn test

  deploy:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - hold:
        type: approval
        requires:
        - build
    - deploy:
        requires:
        - hold
        filters:
          branches:
            only: master